steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/umico-client/telegram-bot/telegram-bot-app:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/umico-client/telegram-bot/telegram-bot-app:${SHORT_SHA}']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'test-telegram-bot'
    - '--image'
    - 'europe-west1-docker.pkg.dev/umico-client/telegram-bot/telegram-bot-app:${SHORT_SHA}'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--quiet'
    - '--set-env-vars'
    - 'ENV=production,OPENROUTER_MODEL=gpt-4o-mini,OPENROUTER_BASE_URL=https://openrouter.ai/api/v1,GCP_PROJECT_ID=umico-client,GCP_REGION=europe-west1,GCP_SERVICE_NAME=test-telegram-bot'
    - '--update-secrets'
    - 'BOT_TOKEN=telegram-bot-token:latest,OPENROUTER_API_KEY=openrouter-api-key:latest'
images:
- 'europe-west1-docker.pkg.dev/umico-client/telegram-bot/telegram-bot-app:${SHORT_SHA}'
